"""MITRE ATT&CK Enterprise (STIX 2.1) loader and CTI-derived statistics.

Turns the official STIX bundle into a compact knowledge base:

* techniques  (id -> name, tactics, platforms, is-subtechnique)
* groups      (G-id -> name, aliases, description, techniques used)
* software    (S-id -> name, techniques used)

Group technique sets include techniques used via the group's software
("group uses S, S uses T" => group uses T), which is how ATT&CK Navigator's
group layers are usually built.

A compact JSON derivative (``gauntlet/data/attack_kb.json``, ~1 MB) is shipped in
the repo so the CLI works without downloading the full 50 MB bundle; it is
regenerated by ``python -m gauntlet kb --stix <bundle>``.
"""
from __future__ import annotations

import json
import re
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

KB_PATH = Path(__file__).resolve().parent / "data" / "attack_kb.json"


def parent(tid: str) -> str:
    return tid.split(".", 1)[0]


@dataclass(frozen=True)
class AttackTechnique:
    id: str
    name: str
    tactics: tuple[str, ...]
    platforms: tuple[str, ...] = ()

    @property
    def is_sub(self) -> bool:
        return "." in self.id


@dataclass
class AttackGroup:
    id: str
    name: str
    aliases: tuple[str, ...]
    description: str
    techniques: set[str] = field(default_factory=set)


@dataclass
class KnowledgeBase:
    version: str
    techniques: dict[str, AttackTechnique]
    groups: dict[str, AttackGroup]
    software: dict[str, dict[str, Any]]
    tactic_order: tuple[str, ...] = ()

    # ------------------------------------------------------------------ stats
    def technique_group_counts(self, rollup: bool = True) -> Counter:
        """How many groups use each technique (parent credited for sub-technique use)."""
        c: Counter = Counter()
        for g in self.groups.values():
            ids = set(g.techniques)
            if rollup:
                ids |= {parent(t) for t in ids}
            c.update(ids)
        return c

    def prevalence(self) -> dict[str, float]:
        """Share of ATT&CK groups with a documented procedure for each technique (0..1)."""
        n = max(len(self.groups), 1)
        return {t: k / n for t, k in self.technique_group_counts().items()}

    def find_group(self, key: str) -> AttackGroup | None:
        k = key.strip().lower()
        for g in self.groups.values():
            if g.id.lower() == k or g.name.lower() == k or k in (a.lower() for a in g.aliases):
                return g
        return None

    def groups_matching(self, pattern: str) -> list[AttackGroup]:
        rx = re.compile(pattern, re.I)
        return sorted((g for g in self.groups.values() if rx.search(g.description)),
                      key=lambda g: g.id)

    def tactic_of(self, tid: str) -> str:
        t = self.techniques.get(tid) or self.techniques.get(parent(tid))
        if not t or not t.tactics:
            return "unknown"
        order = {x: i for i, x in enumerate(self.tactic_order)}
        return sorted(t.tactics, key=lambda x: order.get(x, 99))[0]

    def name_of(self, tid: str) -> str:
        t = self.techniques.get(tid)
        if t:
            if t.is_sub and parent(tid) in self.techniques:
                return f"{self.techniques[parent(tid)].name}: {t.name}"
            return t.name
        return tid

    # ------------------------------------------------------------------ io
    def to_json(self) -> dict[str, Any]:
        return {
            "version": self.version,
            "tactic_order": list(self.tactic_order),
            "techniques": {k: [v.name, list(v.tactics), list(v.platforms)]
                           for k, v in sorted(self.techniques.items())},
            "groups": {k: {"name": g.name, "aliases": list(g.aliases),
                           "description": g.description, "techniques": sorted(g.techniques)}
                       for k, g in sorted(self.groups.items())},
            "software": {k: {"name": s["name"], "techniques": sorted(s["techniques"])}
                         for k, s in sorted(self.software.items())},
        }

    @classmethod
    def from_json(cls, d: dict[str, Any]) -> KnowledgeBase:
        techs = {k: AttackTechnique(k, v[0], tuple(v[1]), tuple(v[2])) for k, v in d["techniques"].items()}
        groups = {k: AttackGroup(k, g["name"], tuple(g["aliases"]), g["description"], set(g["techniques"]))
                  for k, g in d["groups"].items()}
        soft = {k: {"name": s["name"], "techniques": set(s["techniques"])} for k, s in d["software"].items()}
        return cls(d["version"], techs, groups, soft, tuple(d.get("tactic_order", ())))


def _ext_id(obj: dict[str, Any]) -> str | None:
    for ref in obj.get("external_references", []):
        if ref.get("source_name") == "mitre-attack" and ref.get("external_id"):
            return ref["external_id"]
    return None


def _first_sentences(text: str, n: int = 3) -> str:
    text = re.sub(r"\(Citation:[^)]*\)", "", text or "")
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    parts = re.split(r"(?<=[.!?])\s+", text.strip())
    return " ".join(parts[:n]).strip()


def parse_stix(bundle: dict[str, Any], version: str = "") -> KnowledgeBase:
    objs = [o for o in bundle.get("objects", [])
            if not o.get("revoked") and not o.get("x_mitre_deprecated")]
    by_ref: dict[str, dict[str, Any]] = {o["id"]: o for o in objs}
    techniques: dict[str, AttackTechnique] = {}
    stix2tech: dict[str, str] = {}
    groups: dict[str, AttackGroup] = {}
    stix2group: dict[str, str] = {}
    software: dict[str, dict[str, Any]] = {}
    stix2soft: dict[str, str] = {}
    tactic_order: tuple[str, ...] = ()
    shortname_by_ref: dict[str, str] = {}
    for o in objs:
        t = o.get("type")
        eid = _ext_id(o)
        if t == "attack-pattern" and eid:
            tactics = tuple(p["phase_name"] for p in o.get("kill_chain_phases", [])
                            if p.get("kill_chain_name") == "mitre-attack")
            techniques[eid] = AttackTechnique(eid, o.get("name", ""), tactics,
                                              tuple(o.get("x_mitre_platforms", [])))
            stix2tech[o["id"]] = eid
        elif t == "intrusion-set" and eid:
            aliases = tuple(a for a in o.get("aliases", []) if a != o.get("name"))
            groups[eid] = AttackGroup(eid, o.get("name", ""), aliases,
                                      _first_sentences(o.get("description", "")))
            stix2group[o["id"]] = eid
        elif t in ("malware", "tool") and eid:
            software[eid] = {"name": o.get("name", ""), "techniques": set()}
            stix2soft[o["id"]] = eid
        elif t == "x-mitre-tactic":
            shortname_by_ref[o["id"]] = o.get("x_mitre_shortname", "")
        elif t == "x-mitre-matrix" and o.get("tactic_refs"):
            tactic_order = tuple(o["tactic_refs"])
    tactic_order = tuple(shortname_by_ref.get(r, "") for r in tactic_order if r in shortname_by_ref)

    group_soft: dict[str, set[str]] = {}
    for o in objs:
        if o.get("type") != "relationship" or o.get("relationship_type") != "uses":
            continue
        s, d = o.get("source_ref", ""), o.get("target_ref", "")
        if s in stix2group and d in stix2tech:
            groups[stix2group[s]].techniques.add(stix2tech[d])
        elif s in stix2soft and d in stix2tech:
            software[stix2soft[s]]["techniques"].add(stix2tech[d])
        elif s in stix2group and d in stix2soft:
            group_soft.setdefault(stix2group[s], set()).add(stix2soft[d])
    for gid, sids in group_soft.items():
        for sid in sids:
            groups[gid].techniques |= software[sid]["techniques"]
    del by_ref
    if not version:
        coll = next((o for o in bundle.get("objects", []) if o.get("type") == "x-mitre-collection"), None)
        version = str(coll.get("x_mitre_version", "")) if coll else ""
    return KnowledgeBase(version, techniques, groups, software, tactic_order)


def load_stix(path: str | Path) -> KnowledgeBase:
    p = Path(path)
    m = re.search(r"(\d+\.\d+)", p.name)
    return parse_stix(json.loads(p.read_text(encoding="utf-8")), m.group(1) if m else "")


_KB_CACHE: dict[str, KnowledgeBase] = {}


def load_kb(path: str | Path | None = None) -> KnowledgeBase:
    """Load the compact KB (defaults to the one shipped in the package)."""
    p = Path(path) if path else KB_PATH
    key = str(p.resolve())
    if key not in _KB_CACHE:
        if p.suffix == ".json" and p.name.startswith("enterprise-attack"):
            _KB_CACHE[key] = load_stix(p)
        else:
            _KB_CACHE[key] = KnowledgeBase.from_json(json.loads(p.read_text(encoding="utf-8")))
    return _KB_CACHE[key]


def write_kb(kb: KnowledgeBase, path: str | Path = KB_PATH) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(kb.to_json(), separators=(",", ":"), sort_keys=False), encoding="utf-8")
    return p
