"""Score live auditd telemetry with event-level labels (round-3 live job).

The GitHub Actions workflow ``live-telemetry.yml`` runs ``scripts/live_emulate.py`` on an
ephemeral runner: a fixed allowlist of benign discovery commands (``whoami``, ``id``,
``uname -a`` ...) while auditd records ``execve`` and reads of a few files. The emulator
writes ``labels.json`` (command, ATT&CK technique, child PID). This module

1. parses the raw audit log with :mod:`gauntlet.formats`,
2. labels every audit record group (same audit serial) whose ``SYSCALL`` PID belongs to
   an allowlisted command -- *event-level* ground truth, unlike the recording-level
   labels of OTRF/Splunk -- and leaves everything else as background,
3. evaluates Linux Sigma rules event by event, and
4. reports per command/technique whether a rule tagged with that technique fired on its
   own events (measured), whether any rule is tagged for it at all (claimed), and how
   many rules fired on background events (off-target burden).

The package itself never runs commands; only the CI emulator script does.
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

from . import formats, replay, stats
from .attack import parent
from .sigma import SigmaRule


def label_events(lines: list[str], labels: list[dict[str, Any]]) -> tuple[list[tuple[dict, int | None]], int]:
    """Return ``[(event, label_index | None)]`` for every auditd record and synthetic exec event."""
    pid2lab = {str(lab["pid"]): i for i, lab in enumerate(labels) if lab.get("pid")}
    recs = [r for r in (formats.parse_audit_line(x) for x in lines if "msg=audit(" in x) if r]
    group_lab: dict[tuple, int | None] = {}
    for r in recs:
        if r.get("type") == "SYSCALL":
            group_lab[(r.get("timestamp"), r.get("serial"))] = pid2lab.get(str(r.get("pid")))
    out: list[tuple[dict, int | None]] = [(r, group_lab.get((r.get("timestamp"), r.get("serial")))) for r in recs]
    for ev in formats.audit_exec_events(recs):
        out.append((ev, pid2lab.get(str(ev.get("ProcessId")))))
    return out, len(recs)


def score(audit_log: Path, labels_path: Path, rules: list[SigmaRule]) -> dict[str, Any]:
    labels = json.loads(Path(labels_path).read_text(encoding="utf-8"))["commands"]
    lines = Path(audit_log).read_text(encoding="utf-8", errors="replace").splitlines()
    evs, n_records = label_events(lines, labels)
    idx = replay.RuleIndex(rules)
    by_id = {r.id: r for r in rules}
    fired_on: dict[int, set[str]] = defaultdict(set)
    n_lab: dict[int, int] = defaultdict(int)
    bg_rules: set[str] = set()
    bg_events = 0
    for ev, li in evs:
        _, _, hits = idx.evaluate([ev])
        if li is None:
            bg_events += 1
            bg_rules |= set(hits)
        else:
            n_lab[li] += 1
            fired_on[li] |= set(hits)
    rows = []
    for i, lab in enumerate(labels):
        t = lab["technique"]
        tagged = [r.id for r in rules if parent(t) in {parent(x) for x in r.techniques}]
        on = sorted(by_id[r].title for r in fired_on[i] if parent(t) in {parent(x) for x in by_id[r].techniques})
        off = sorted(by_id[r].title for r in fired_on[i] if r not in {x for x in tagged})
        rows.append({"command": " ".join(lab["argv"]), "technique": t, "labelled_events": n_lab[i],
                     "claimed": bool(tagged), "measured": bool(on), "on_target_rules": on,
                     "other_rules_fired": off})
    techs: dict[str, dict[str, bool]] = {}
    for r in rows:
        d = techs.setdefault(r["technique"], {"claimed": False, "measured": False})
        d["claimed"] |= r["claimed"]
        d["measured"] |= r["measured"]
    m = sum(v["measured"] for v in techs.values())
    c = sum(v["claimed"] for v in techs.values())
    return {"audit_records": n_records, "events": len(evs), "labelled_events": sum(n_lab.values()),
            "background_events": bg_events, "rules": len(rules),
            "background_rules_fired": sorted(by_id[r].title for r in bg_rules),
            "commands": rows, "techniques": techs,
            "technique_coverage": round(m / len(techs), 4) if techs else 0.0,
            "technique_coverage_ci95": list(stats.wilson(m, len(techs))),
            "claimed_coverage": round(c / len(techs), 4) if techs else 0.0}


def render_md(rep: dict[str, Any]) -> str:
    L = ["# Live auditd telemetry vs replayed recordings", "",
         "Generated by `python -m gauntlet live` in the `live-telemetry` workflow"
         + (f" (run {rep['run_id']})" if rep.get("run_id") else "") + ".", ""]
    for name, r in rep["rulesets"].items():
        L += [f"## Rule set: {name} ({r['rules']} Linux rules)", "",
              f"{r['audit_records']} audit records -> {r['labelled_events'] + r['background_events']} events "
              f"({r['labelled_events']} labelled to allowlisted commands, {r['background_events']} background). Live technique coverage "
              f"{100 * r['technique_coverage']:.0f}% of {len(r['techniques'])} techniques "
              f"(claimed by tags: {100 * r['claimed_coverage']:.0f}%). Rules firing on background: "
              f"{len(r['background_rules_fired'])}.", "",
              "| Command | Technique | Labelled events | Claimed | Live: detected | Replayed (Splunk): detected |",
              "|---|---|---:|:---:|:---:|:---:|"]
        rp = rep.get("replayed", {}).get(name, {})
        for c in r["commands"]:
            rv = rp.get(c["technique"])
            rv_s = "n/a (no recording)" if rv is None else ("yes" if rv else "no")
            L.append(f"| `{c['command']}` | {c['technique']} | {c['labelled_events']} | "
                     f"{'yes' if c['claimed'] else 'no'} | {'yes' if c['measured'] else 'no'} | {rv_s} |")
        L.append("")
    return "\n".join(L)
